### ISSUE TITLE
TotalWorldWarManual.pdf could not be uploaded

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/total_world_war#1]
The file is 150MB, above the single file limit of 100MB for upload. For now it's not uploaded (and can still be found in SVN packaged with the map zip)

**Comment by RoiEXLab** [comment]
@ron-murhammer This should be closed per #4 
See https://github.com/triplea-maps/total_world_war/blob/0c60b3b84775561d07d60b7bfb3611ca6b710267/TWW_lossy_new.pdf for the redone PDF, that has been compressed with lossy compression, to drastically reduce the filesize. The underlying PNGs however are still lossless, so we can increase the quality again if we want.
